name: Welcome New Contributors



on:

  pull_request_target:

    types: [opened]



jobs:

  greet:

    runs-on: ubuntu-latest

    steps:

      - name: Greet the user

        run: echo "👋 Welcome to the repository! Thanks for your contribution."

